### ISSUE TITLE
Where to include the gem for use in views?

### ISSUE THREAD

**Issue by subvertallchris** [neo4jrb/neo4j-will_paginate_redux#1]
Reported by @chrisgogreen:

In a rails 4 app where should I "require 'neo4j-will_paginate_redux'"?
I am getting:

```
undefined method `paginate' for #<#
<Class:0x000000044ca050>:0x000000044c8368>
```

when I call paginate in the view. But the call to paginate in my controller succeeds:

```
@items = Item.all.paginate(page: params[:page])
```

**Comment by subvertallchris** [comment]
If your gemfile has it set to `require: false`, require it in your controller and then use it like this:

``` ruby
# students_controller.rb
def index
  @students = Student.all.paginate(page: params[:page], per_page: 10)
end

# in the view
<%= will_paginate @students %>
```

Does that work for you?

**Comment by subvertallchris** [comment]
https://github.com/neo4jrb/neo4j/issues/540#issuecomment-62801881

**Comment by ghost** [comment]
No, same problem. The readme says `<%= paginate @students %>`, not will_paginate. I also tried it with require:false, same error.

**Comment by subvertallchris** [comment]
Ah crap, I'll fix that. I adapted the original docs, so I'll just say that it was his fault. ;-)

**Comment by ghost** [comment]
It's interesting that I can require the file in my controller and use the paginate method in the index action, but not in the view with paginate @students or will_paginate @students. Thanks for looking into it.

**Comment by subvertallchris** [comment]
I misread "No, same problem" as "no problem." I guess I'm projecting what I want to see! Haha.

That's weird... Could you post some of your code?

**Comment by subvertallchris** [comment]
Ah! Ya know what it is? Add `gem 'will_paginate'` to your Gemfile. I have the same problem when I remove it from mine.

**Comment by ghost** [comment]
Great! Thanks! problem resolved.

**Comment by subvertallchris** [comment]
Gimme a sec and I'm gonna push a new version of the gem that takes care of it for you. `will_paginate` is already installed for you, it's just not required correctly within redux.

**Comment by subvertallchris** [comment]
There you go. It's on Rubygems as 0.3.3.

**Comment by ghost** [comment]
new version works for me as well, thanks again.

**Comment by pdipietro** [comment]
@subvertallchris 

gem 'neo4j-will_paginate' returns the following error in the latest environment:

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    neo4j-will_paginate (>= 0) ruby depends on
      activesupport (~> 3.0) ruby

    rails (= 4.2.0.beta4) ruby depends on
      activejob (= 4.2.0.beta4) ruby depends on
        activesupport (4.2.0.beta4)
```

the redux version install correctly.
