### ISSUE TITLE
Does not work with query_as

### ISSUE THREAD

**Issue by chesterl** [neo4jrb/neo4j-will_paginate_redux#3]
I tried this last night and found a query that doesn't work

This does not work
Model.query_as(:a).where( ...)

but the :as works
Model.as(:a).where(...)

**Comment by subvertallchris** [comment]
"Doesn't work" doesn't tell us anything! :anger: What is the error?

Loaded question: I already know the error. ;-) Core::Query does not support pagination, only QueryProxy does. We should be able to adapt Core::Query to support it very easily but it's not super high on the priorities list.

**Comment by chesterl** [comment]
Haha crap. I forgot to put that in.

Yes pagination isn't supported on the object

`undefined method`paginate' for #<Neo4j::Core::Query`

**Comment by subvertallchris** [comment]
You know what you must do.

(Disclaimer: I have been pushing Chester to contribute to the gem for a while now. I'm not just being a jerk to a total stranger who opened an issue.)

**Comment by subvertallchris** [comment]
Can we close this?

**Comment by chesterl** [comment]
Yep
